#███████╗    ██████╗      █████╗       ███████╗                  
#██╔════╝    ██╔══██╗    ██╔══██╗      ██╔════╝                  
#███████╗    ██████╔╝    ███████║      ███████╗                  
#╚════██║    ██╔══██╗    ██╔══██║       ╚════██║                  
#███████║    ██║  ██║    ██║  ██║      ███████║                  
#╚══════╝    ╚═╝  ╚═╝    ╚═╝  ╚═╝      ╚═════╝       

#This acutally uses the SRA accession numbers instead of using local genomes


samples:

# ok, this sample, per the sra metadata is an actual metagenome
#- SRR5935808

- SRR5962882
- SRR5962883
- SRR5962884

#- SRR5962885
#- SRR5962886
#- SRR5962887



#- SRR3051889
#- SRR3051890
#- SRR3051891
#- SRR3051892
#- SRR3051893
 
outdir: outputs.mgx
metagenome_trim_memory: 11e9
prefetch_memory: 11e9
# ^ 1e9 = 1 gig

# for mgx, when looking for bacteria
#sourmash_databases:
#- gtdb-rs202.genomic-reps.k31.sbt.zip

### for viromes:
#sourmash_database_ksize: 21
#sourmash_scaled: 200
#sourmash_database_threshold_bp: 100

sourmash_compute_ksizes:
- 21
- 31
- 51

#prefetch_memory: 20e9

sourmash_databases:
- /group/ctbrowngrp/gtdb/databases/gtdb-rs202.genomic-reps.k31.zip


taxonomies:
- /group/ctbrowngrp/genbank/all_genbank_lineages.20200727.csv
