# data copied from /home/hehouts/dynamic-duos-virome/snakecrate/data/raw_data/vir/abundtrim

prevent_sra_download: true
samples:
- SM_6UG79
- SM_71WY3
- SM_7CRX4
- SM_6X9WV
- SM_76CAU
- SM_7CP3H
- SM_7EWTT
- SM_6OSOR
- SM_6Y2V3
- SM_77VQ4
- SM_7EWUL
- SM_6WJN6
- SM_6X9X4
- SM_6YAZO
- SM_6ZKSM
- SM_71WXM
- SM_73JY4
- SM_76EOJ
- SM_791BX
- SM_7BF2J
- SM_7CRJ8
- SM_7EWUH
- SM_7GYJO
- SM_7IL1E
- SM_7KPUR
- SM_7MOQJ
- SM_6WOCE
- SM_6ZEVI
- SM_7AA2E
- SM_7BP5L
- SM_7I1G8
- SM_7K25Z

outdir: outputs.s5_vir
# metagenome_trim_memory: (gtdb 1e9?)
prefetch_memory: 20e9

# for mgx, when looking for bacteria
#sourmash_databases:
#- gtdb-rs202.genomic-reps.k31.sbt.zip

sourmash_database_ksize: 21
sourmash_scaled: 200
sourmash_database_threshold_bp: 100

sourmash_databases:
- /group/ctbrowngrp/scratch/ctbrown/gut-phage-db.grist/GPD_sequences.zip

local_databases_info:
- /group/ctbrowngrp/scratch/ctbrown/gut-phage-db.grist/GPD_sequences.info.csv

taxonomies:
- /group/ctbrowngrp/genbank/all_genbank_lineages.20200727.csv
