#LOOK OUT! ITS A

#  ███████╗    ███╗   ██╗     █████╗     ██╗  ██╗    ███████╗    ███████╗    ██╗    ██╗         ███████╗
#  ██╔════╝    ████╗  ██║    ██╔══██╗    ██║ ██╔╝    ██╔════╝    ██╔════╝    ██║    ██║         ██╔════╝
#  ███████╗    ██╔██╗ ██║    ███████║    █████╔╝     █████╗      █████╗      ██║    ██║         █████╗  
#  ╚════██║    ██║╚██╗██║    ██╔══██║    ██╔═██╗     ██╔══╝      ██╔══╝      ██║    ██║         ██╔══╝  
#  ███████║    ██║ ╚████║    ██║  ██║    ██║  ██╗    ███████╗    ██║         ██║    ███████╗    ███████╗
#  ╚══════╝    ╚═╝  ╚═══╝    ╚═╝  ╚═╝    ╚═╝  ╚═╝    ╚══════╝    ╚═╝         ╚═╝    ╚══════╝    ╚══════╝
                                                                                                     
                                                                                                    
                               
# █████ set variables ██████

FILES = ["CSM67UBN.tar",
    "CSM5FZ3X_P.fastq.gz",
    "CSM5MCVL.tar",
    "CSM5FZ3Z_P.fastq.gz",
    "CSM5MCVN.tar",
    "CSM5FZ46_P.fastq.gz",
    "CSM79HJY.tar",
    "CSM67UBH.tar",
    "CSM79HJW.tar",
    "CSM5FZ42_P.fastq.gz",
    "CSM5FZ44_P.fastq.gz",
    "CSM67UBF.tar",
    "CSM5MCVJ_P.fastq.gz",
    "CSM67UBR.tar",
    "CSM5FZ3T_P.fastq.gz"]


  #GENERATE SAMPLE LIST
INPUT_DATA = "sample_lists/sub_1_mv.txt"
SAMPLES = [x.strip().split(".tar")[0] for x in open(INPUT_DATA, 'r')]

    #K SIZES
K_SIZES = ["21","31","51"]

    ###more realistic for prot:    
PROT_K_SIZES = ["5","7","10"]

    #SUBSAMPLE
    ###takes first 3 samples
SAMPLES = SAMPLES[:1]

#█████ set variables ███████████████

