#███╗   ███╗███████╗████████╗ █████╗  ██████╗ ███████╗███╗   ██╗ ██████╗ ███╗   ███╗███████╗ 
#████╗ ████║██╔════╝╚══██╔══╝██╔══██╗██╔════╝ ██╔════╝████╗  ██║██╔═══██╗████╗ ████║██╔════╝ 
#██╔████╔██║█████╗     ██║   ███████║██║  ███╗█████╗  ██╔██╗ ██║██║   ██║██╔████╔██║█████╗   
#██║╚██╔╝██║██╔══╝     ██║   ██╔══██║██║   ██║██╔══╝  ██║╚██╗██║██║   ██║██║╚██╔╝██║██╔══╝   
#██║ ╚═╝ ██║███████╗   ██║   ██║  ██║╚██████╔╝███████╗██║ ╚████║╚██████╔╝██║ ╚═╝ ██║███████╗ 
#╚═╝     ╚═╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝  ╚═══╝ ╚═════╝ ╚═╝     ╚═╝╚══════╝ 
#                                                                                            
#██╗   ██╗███████╗                                                                           
#██║   ██║██╔════╝                                                                           
#██║   ██║███████╗                                                                           
#╚██╗ ██╔╝╚════██║                                                                           
# ╚████╔╝ ███████║                                                                           
#  ╚═══╝  ╚══════╝                                                                           
#                                                                                            
# ██████╗ ██╗   ██╗████████╗    ██████╗ ██╗  ██╗ █████╗  ██████╗ ███████╗    ██████╗ ██████╗ 
#██╔════╝ ██║   ██║╚══██╔══╝    ██╔══██╗██║  ██║██╔══██╗██╔════╝ ██╔════╝    ██╔══██╗██╔══██╗
#██║  ███╗██║   ██║   ██║       ██████╔╝███████║███████║██║  ███╗█████╗      ██║  ██║██████╔╝
#██║   ██║██║   ██║   ██║       ██╔═══╝ ██╔══██║██╔══██║██║   ██║██╔══╝      ██║  ██║██╔══██╗
#╚██████╔╝╚██████╔╝   ██║       ██║     ██║  ██║██║  ██║╚██████╔╝███████╗    ██████╔╝██████╔╝
# ╚═════╝  ╚═════╝    ╚═╝       ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝    ╚═════╝ ╚═════╝ 
#
samples:
- SRR5962882
- SRR5962883
- SRR5962884

outdir: outputs.mgxVSgpdb
metagenome_trim_memory: 15e9
prefetch_memory: 15e9

sourmash_database_ksize: 21
sourmash_scaled: 100
sourmash_database_threshold_bp: 100
sourmash_compute_ksizes: 
- 21
#prefetch_memory: 20e9

sourmash_databases:
- /group/ctbrowngrp/virus-references/gut-phage-db/GPD_sequences.zip
taxonomies:
- /group/ctbrowngrp/virus-references/gut-phage-db/GPD_metadata.tsv
