---
title: "ihmp_metadata Process_2"
output: html_document
---


### Setup

```{r setwd, include=FALSE}
#setwd("/Users/hehouts/Projects/2020-IBD-Virome")
```

```{r trunc-output, include=FALSE}
## save the built-in output hook
#hook_output <- knitr::knit_hooks$get("output")

## set a new output hook to truncate text output
#knitr::knit_hooks$set(output = function(x, options) {
#  if (!is.null(n <- options$out.lines)) {
#    x <- xfun::split_lines(x)
#    if (length(x) > n) {
#      # truncate the output
#      x <- c(head(x, n), "....\n")
#    }
#    x <- paste(x, collapse = "\n")
#  }
#  hook_output(x, options)
#})
```

### Expanding the metat data for part. list

grab all the data from the og metadata sheet matching these guys:
```{}
C3002
C3003
C3008
C3010
C3016
C3017
C3027
C3031
C3034
C3037
E5009
H4006
H4013
H4015
H4016
H4017
H4018
H4024
H4030
H4035
H4038
H4039
M2025
M2028
M2064
M2068
M2069
M2077
P6010
P6016
P6018
P6024
P6028
P6037
```

```{r}
partp_list <- list("C3002", "C3003", "C3008", "C3010", "C3016", "C3017", "C3027", "C3031", "C3034", "C3037", "E5009", "H4006", "H4013", "H4015", "H4016", "H4017", "H4018", "H4024", "H4030", "H4035", "H4038", "H4039", "M2025", "M2028", "M2064", "M2068", "M2069", "M2077", "P6010", "P6016", "P6018", "P6024", "P6028", "P6037")


partp_metadata <- og_metadata %>%
    
    rename(abx=`Antibiotics`) %>%
    rename(abx_since_last_visit=`Has the subject used any antibiotics since the last visit?`) %>%
    rename(abx_past_6_mo=`In the past 6 months, have you used antibiotics?`) %>%
    rename(abx_other=`Other Antibiotic:`) %>%
    rename(abx_other_reason_for_stopping=`Reason for stopping other antibiotic:`) %>%

    rename(research_project=`Research Project`) %>%
    rename(participant_id=`Participant ID`) %>%
    rename(external_id=`External ID`) %>%
    rename(age_at_diagnosis=`Age at diagnosis`) %>%

    arrange(participant_id, week_num, data_type) %>%
  
    subset(participant_id %in% partp_list)

#partp_metadata <- subset(partp_metadata,partp_metadata$participant_id %in% x) 
  
#partp_metadata,participant_id %in% ["P6024", "P6028", "P6037"])
  
  
print(partp_metadata)
```

## partp_metadata is gold


