---
title: "Subject Subsetting"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) 
```



## Load libraries
```{r, echo=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
```


## load data 
This .csv was pulled from the ibdmdb webpage?
```{r}
setwd("/Users/hehouts/projects/dynamic-duos/R")

reference_metadata <- readr::read_csv("../metadata/ibdmdb-metadata-manifests/ihmp_metadata.csv", show_col_types = F)
#tidy names
metadata <- clean_names(reference_metadata)

head(metadata, 3)
```

## Three subject subset
```{r}
subset <- metadata%>%
  filter(participant_id == "C3002"
        | participant_id == "C3003"
        | participant_id == "C3008"
        )%>%
  arrange(participant_id, week_num)
subset
```
## metagenomics data

```{r}
subset_mgx <- subset%>%
  filter(data_type=="metagenomics") %>%
  arrange(participant_id, week_num)
subset_mgx
```




## vrmx data

```{r}
subset_vrmx <- metadata%>%
  filter(data_type=="viromics") %>%
  arrange(participant_id, week_num)
subset_vrmx
```


## One subject, mgx & vrmx combined
```{r}
c3002_metadata <- subset%>%
  filter(participant_id == "C3002")%>%
  filter(data_type=="viromics" | data_type=="metagenomics")%>%
  arrange(participant_id, data_type, week_num)%>%
  select(external_id, week_num, participant_id, data_type)

c3002_metadata
```

```{r}
c3002_metadata %>% select(external_id)
```



```
CSM5FZ3T_P.tar			
CSM5FZ3X_P.tar			
CSM5FZ3Z_P.tar			
CSM5FZ42_P.tar			
CSM5FZ44_P.tar			
CSM5FZ46_P.tar			
CSM5MCVJ_P.tar			
CSM5MCVL.tar		
CSM5MCVN.tar		
CSM67UBF.tar
CSM67UBH.tar				
CSM67UBN.tar				
CSM67UBR.tar				
CSM79HJW.tar				
CSM79HJY.tar

CSM5MCVN.tar				
CSM67UBH.tar				
CSM67UBN.tar				
CSM79HJW.tar
```