prevent_sra_download: true
samples:
- CSM79HGP

outdir: outputs.smp1_mgx

prefetch_memory: 20e9

# for mgx, when looking for bacteria
#sourmash_databases:
#- gtdb-rs202.genomic-reps.k31.sbt.zip

sourmash_compute_ksizes:
- 21
- 31
- 51

#prefetch_memory: 20e9

sourmash_databases:
- /group/ctbrowngrp/gtdb/databases/gtdb-rs202.genomic-reps.k31.zip

taxonomies:
- /group/ctbrowngrp/genbank/all_genbank_lineages.20200727.csv
